---
title: "Compilation"
author: "Akshay"
output: html_document
---

# Reading all the data and previous results.
```{r}
# Reading time series forecasting results
TS_data <- read.csv("C:/Users/akvt5/OneDrive/Documents/Academics/UU Course Docs/Semester 3/Data/TS_pred.csv")
# Reading technical analysis results
Tech_data <- read.csv("C:/Users/akvt5/OneDrive/Documents/Academics/UU Course Docs/Semester 3/Data/Tech_pred.csv")
# Reading the original data
bajaj_data <- read.csv("C:/Users/akvt5/OneDrive/Documents/Academics/UU Course Docs/Semester 3/Data/BAJAJ-AUTO.NS.csv")
dim(bajaj_data)
str(bajaj_data)
summary(bajaj_data)

# Converting date format from character to datetime
bajaj_data$Date <- as.Date(bajaj_data$Date, format = "%d-%m-%Y")

# Checking for missing values
sum(is.na.data.frame(bajaj_data$MACD_.1))
# Removing the rows with NA's
bajaj_data <- bajaj_data[27:1235,1:17]


# Filtering out final data which was the test data used in previous analysis
final_data <- bajaj_data[846:1209,1:17]
# Binding previous analysis results into the final data as new columns/features
final_data <- cbind(final_data, ts_pred = unlist(TS_data))
final_data <- cbind(final_data, tech_pred = unlist(Tech_data))


# Splitting the data into Train and Test
library(caret)
set.seed(143)
train_index <- createDataPartition(final_data$Close, p = 0.8, list = FALSE)
train_data <- final_data[train_index, ]
test_data <- final_data[-train_index, ]



```


# Building Models
```{r}
# 1) Simple linear regression
model_1 <- lm(Close ~ ts_pred + tech_pred, data = train_data)
summary(model_1)

# Predicting values for test data
predict_1 <- predict(model_1, newdata = test_data)

# Measuring the performance
print("R^2 value on test data")
actual_values <- test_data$Close
(rsquared <- 1 - sum((actual_values - predict_1)^2) / sum((actual_values - mean(actual_values))^2))


```


